name: Sync To Gitee And GitCode

on: [push,delete,create]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: "${{ secrets.GITEE_RSA_PRIVATE_KEY }}"
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:KingPrimes/ZeroKingBot.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:KingPrime/zero-king-bot.git